# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.9

test:
  before_script:
    - pip install flake8 pytest
    - pip install -r requirements.txt
  script:
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - python -m pytest

pages:
  script:
    - pip install -r requirements-docs.txt
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
