image: harbor.eds.aphp.fr/public/python:3.7

default:
  tags:
    - k8s-small-generic

test:
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - black --check .
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - python -m pytest --cov edsnlp --junitxml=report.xml --html=report.html --self-contained-html
  after_script:
    - coverage xml -o coverage.xml
    - coverage html -d htmlcov
  artifacts:
    paths:
      - htmlcov/
      - coverage.xml
      - report.html
      - report.xml
    reports:
      cobertura: coverage.xml
      junit: report.xml

pages:
  script:
    - apt-get update
    - apt-get install -y pandoc
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
