image: harbor.eds.aphp.fr/plateforme-datascience/pyspark-tests:3.7

default:
  tags:
    - k8s-small-generic

test:
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -r requirements-setup.txt
    - pip install pyspark
    - PYTHONPATH="$PWD:$PYTHONPATH" python scripts/conjugate.py
    - apt-get update
    - apt install -y git
  script:
    - pre-commit install
    - pre-commit run --all-files
    - python -m pytest --cov edsnlp --junitxml=report.xml --html=report.html --self-contained-html
  after_script:
    - coverage xml -o coverage.xml
    - coverage html -d htmlcov
  artifacts:
    paths:
      - htmlcov/
      - coverage.xml
      - report.html
      - report.xml
    reports:
      cobertura: coverage.xml
      junit: report.xml

pages:
  script:
    - apt-get update
    - apt-get install -y pandoc make
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - pip install pyspark
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

package:
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install -r requirements-setup.txt
    - PYTHONPATH="$PWD:$PYTHONPATH" python scripts/conjugate.py
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  when: manual
