image: python:3.9

default:
  tags:
    - k8s-small-generic

test:
  before_script:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - black --check .
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - python -m pytest --cov edsnlp --junitxml=report.xml
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: report.xml

pages:
  script:
    - pip install -r requirements.txt
    - pip install -r requirements-docs.txt
    - cd docs ; make html
    - mv _build/html/ ../public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
