site_name: EDS-NLP

repo_url: https://github.com/aphp/edsnlp
repo_name: aphp/edsnlp

# copyright: Copyright &copy; 2022 – Assistance Publique - Hôpitaux de Paris

# extra:
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/aphp

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode

  # logo: assets/logo/edsnlp.svg
  favicon: assets/logo/edsnlp.svg
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    # - navigation.tabs
    - navigation.top
    - content.code.annotate

nav:
  # - Overview:
  - index.md
  - home/demo.md
  - home/spacy101.md
  - Tutorials:
      - home/tutorials/index.md
      - home/tutorials/matching-a-terminology.md
      - home/tutorials/qualifying-entities.md
      - home/tutorials/detecting-dates.md
      - home/tutorials/multiple-texts.md
  - Advanced tutorials:
      - home/advanced-tutorials/index.md
      - home/advanced-tutorials/word-vectors.md
      - home/advanced-tutorials/fastapi.md
      - Creating a pipeline: https://spacy.io/usage/processing-pipelines#custom-components" target="_blank
  # - Development:
  #     - development/index.md
  - Pipelines:
      - pipelines/index.md
      - pipelines/architecture.md
      - Core Pipelines:
          - pipelines/core/index.md
          - pipelines/core/matcher.md
          # - pipelines/core/advanced-matcher.md
          - pipelines/core/normalisation.md
          - pipelines/core/endlines.md
          - pipelines/core/sentences.md
      - Qualifiers:
          - pipelines/qualifiers/index.md
          - pipelines/qualifiers/negation.md
          - pipelines/qualifiers/family.md
          - pipelines/qualifiers/hypothesis.md
          - pipelines/qualifiers/reported-speech.md
          - pipelines/qualifiers/history.md
      - Miscellaneous:
          - pipelines/misc/index.md
          - pipelines/misc/dates.md
          - pipelines/misc/consultation-dates.md
          - pipelines/misc/sections.md
          - pipelines/misc/reason.md
      - Named Entity Recognition:
          - pipelines/ner/index.md
          - pipelines/ner/score.md
  # - Utilities:
  #     - utilities/index.md
      # - Processing:
      #     - utilities/processing/index.md
      #     - utilities/processing/single.md
      #     - utilities/processing/multi.md
      #     - utilities/processing/spark.md
  - Connectors:
      - utilities/connectors/index.md
      - utilities/connectors/brat.md
      - utilities/connectors/omop.md
      # - utilities/connectors/labeltool.md
      # - utilities/regex.md
      # - utilities/evaluation.md
  - Code Reference: reference/
  - development/contributing.md
  - development/changelog.md

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

plugins:
  - termynal
  # - charts
  - search
  - bibtex:
      bib_file: "docs/references.bib"
  - gen-files:
      scripts:
        - docs/generate_reference.py
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            docstring_section_style: spacy
            heading_level: 3
            members_order: source
            show_root_toc_entry: false
      watch:
        - "edsnlp"
  - literate-nav:
      nav_file: SUMMARY.md
  # - img2fig
  # - mknotebooks:
  #     execute: false
  #     timeout: 100
  #     allow_errors: false

markdown_extensions:
  - admonition
  - pymdownx.superfences
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: vegalite
  #         class: vegalite
  #         format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
