[tool.poetry]
name = "edsnlp"
version = "0.4.0a1"
description = ""
authors = [
    "Basile Dura <basile.dura-ext@aphp.fr>",
    "Thomas Petit-Jean <thomas.petitjean-ext@aphp.fr>",
    "Ariel Cohen <ariel.cohen-ext@aphp.fr>",
]
license = "BSD-3-Clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7.1"
spacy = "^3.2.1"
numpy = ">=1.21"
loguru = "^0.6.0"
tqdm = "^4.62.3"
scikit-learn = "^1.0.1"
pandas = "^1.2"
dateparser = "^1.1.0"
typer = "^0.4.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.0"
black = "^22.1.0"
jupytext = "^1.13.6"
pre-commit = "^2.17.0"
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
pytest-html = "^3.1.1"
ipython = "^7.0"
myst-parser = "^0.16.1"
nbsphinx = "^0.8.8"
Sphinx = "^4.4.0"
sphinx-autobuild = "^2021.3.14"
sphinx-rtd-theme = "^1.0.0"
sphinxcontrib-bibtex = "^2.4.1"
mlconjug3 = "^3.8.2"
pyspark = "^3.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
