name: Tests and Linting

on:
  pull_request:
  push:
    branches: [master]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files

  Pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        scripts/install.sh
        pip install pyspark
    - name: Test with Pytest on Python ${{ matrix.python-version }}
      run: |
        python -m pytest --cov edsnlp --junitxml=report.xml --html=report.html --self-contained-html

  Installation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install library
      run: |
        pip install .
